#define MODBUS_RTU_DEBUG_MESSAGES   0

#define MODBUS_RTU_RXBUFFER_MAX     255

#define MODBUS_RTU_TXBUFFER_MAX     255

#define MODBUS_RTU_ADU_OFFSET       0
#define MODBUS_RTU_PDU_OFFSET       MODBUS_RTU_ADU_OFFSET + 1

#define MODBUS_RTU_ADDRESS          MODBUS_RTU_ADU_OFFSET
#define MODBUS_RTU_FUNCTION         MODBUS_RTU_PDU_OFFSET
#define MODBUS_RTU_DATA             MODBUS_RTU_PDU_OFFSET + 1

#define MODBUS_RTU_MIN_TICK         28

#define MODBUS_RTU_TIMEOUT          1000

#define MODBUS_USE_WATCH_DOG        1