#define PWM_FLAG_NOFLAG     0x00

#define PWM_FLAG_INMOTION   0x01
#define PWM_FLAG_HASBREAK   0x02

#define PWM_FLAG_HASENABLE  0x04
#define PWM_FLAG_HASENPIN   0x08
#define PWM_FLAG_ENINVERT   0x10

#define PWM_FLAG_DUTYINVERT 0x20