//Flags
#define BUTTON_FLAG_RETURNS_ISPRESSED       0x001
#define BUTTON_FLAG_RETURNS_LONGPRESS       0x002
#define BUTTON_FLAG_RETURNS_ONTOUCH         0x004
#define BUTTON_FLAG_RETURNS_ONUPEVENT       0x008
#define BUTTON_FLAG_ISPRESSED               0x100
#define BUTTON_FLAG_ISPRESSED_CHECK         0x200
#define BUTTON_FLAG_ISHELD_EVALUATED        0x400